"$schema" = 'https://starship.rs/config-schema.json'

format = """$time $directory$all"""
continuation_prompt = '▶▶ '

[time]
disabled = false
time_format = "%H:%M"
format = "[$time]($style)"

[cmd_duration]
min_time = 0
show_milliseconds = true
