[shell]
polkit_agent = true

[weather]
enabled = true

[location]
auto_locate = true

[nightlight]
enabled = true

[lockscreen]
enabled = true

[lockscreen_widgets]
enabled = true

[idle.behavior.lock]
timeout = 600
action = "lock"
enabled = true

[idle.behavior.screen-off]
timeout = 660
action = "screen_off"
enabled = true

[idle.behavior.suspend]
timeout = 900
action = "lock_and_suspend" # or action = "suspend" with lock_before_suspend = false

[battery]
warning_threshold = 20

[bar.default]
margin_ends = 50
margin_edge = 0
margin_opposite_edge = 5
start  = ["launcher", "wallpaper", "workspaces", "media"]
center = ["clock"]
end    = ["tray", "notifications", "clipboard", "volume", "brightness", "battery", "network", "session"]
