[keybinds]
validate = ["return", "kp_enter"]
cancel   = ["escape"]
left     = ["left"]
right    = ["right"]
up       = ["up"]
down     = ["down"]
tab_next = ["tab"]
tab_previous = ["shift+tab", "iso_left_tab"]
